const { JSDOM, VirtualConsole } = require("jsdom");
const fs = require("fs");
const html = fs.readFileSync(process.argv[2], "utf8");
const errors = [];
const dom = new JSDOM(html, { runScripts: "dangerously", url: "https://example.test/energy/", virtualConsole: new VirtualConsole().on("jsdomError", e => errors.push(String(e))) });
const w = dom.window, d = w.document;
const t = () => d.getElementById("doc").textContent;
const ok = (c, m) => { if (!c) { console.log("FAIL:", m); process.exitCode = 1; } else console.log("ok:", m); };
const D = JSON.parse(d.getElementById("data").textContent);
const hover = (el, type) => el.dispatchEvent(new w.MouseEvent(type, { bubbles: true, clientX: 50, clientY: 50 }));

ok(errors.length === 0, "no script errors " + errors.join(";"));
ok(t().includes("Energy and PUE") && d.querySelectorAll(".tile").length === 4, "title and four tiles");
ok(t().includes(D.month.pue.toFixed(3)) && t().includes(D.report.pue.toFixed(3)) && t().includes(D.kpi.actual.toFixed(3)), "month, reported, and 52-week PUE shown");
ok(d.querySelector(".flag.bad") && t().includes("Does not reconcile with the meters (EN-F1)"), "the report mismatch is flagged on its tile");
ok(t().includes("a Key Measurement with no credits"), "PUE is a KPI, not a credit");
ok(d.querySelectorAll("#c1 .hit").length === 13 && d.querySelectorAll("#c2 .hit").length === 28, "13 periods and 28 days, each with a hover target");
ok(d.querySelectorAll(".legend span").length >= 5, "legends name every series");
const bar = d.querySelector("#c1 .hit[data-i='12']");
hover(bar, "mousemove");
const tip1 = d.querySelector("#c1 .tip");
ok(tip1.style.display === "block" && tip1.textContent.includes("this month") && tip1.textContent.includes("Cooling"), "a period bar shows its split on hover");
hover(bar, "mouseleave");
ok(tip1.style.display === "none", "and hides it after");
hover(d.querySelector("#c2 .hit[data-i='24']"), "mousemove");
ok(d.querySelector("#c2 .tip").textContent.includes("Generators") && d.querySelector("#c2 .cross").getAttribute("visibility") === "visible", "the outage day shows generator energy, with a crosshair");
ok(t().includes("CH-03 free cooling off"), "the lockout is shaded on the daily chart");
const tb = d.getElementById("tbl1"), t1 = d.getElementById("t1");
ok(t1.hidden, "period table hidden at first");
tb.click();
ok(!t1.hidden && tb.textContent === "Hide table" && t1.querySelectorAll("tr").length === 14, "the table view lists every period");
ok(t().includes("EN-F1") && t().includes("EN-F2") && t().includes("OT-EN-03"), "both findings with their contract terms");
ok(t().includes("not that anyone misled"), "a finding is framed as records that do not reconcile");
ok(t().includes("PM-0015") && t().includes("PM-0014"), "the free-cooling log lists every lockout");
ok(d.querySelector('a[href="https://www.iso.org/standard/30134-2"]') && t().includes("ISO/IEC 30134-2:2026"), "cites the standard");
ok(errors.length === 0, "still no script errors " + errors.join(";"));
