const { JSDOM, VirtualConsole } = require("jsdom");
const fs = require("fs");
const html = fs.readFileSync(process.argv[2], "utf8");
const errors = [];
const dom = new JSDOM(html, { runScripts: "dangerously", url: "https://example.test/patterns/", virtualConsole: new VirtualConsole().on("jsdomError", e => errors.push(String(e))) });
const d = dom.window.document;
const t = () => d.getElementById("doc").textContent;
const ok = (c, m) => { if (!c) { console.log("FAIL:", m); process.exitCode = 1; } else console.log("ok:", m); };
const tab = id => [...d.querySelectorAll("#tabs button")].find(b => b.dataset.view === id);

ok(errors.length === 0, "no script errors " + errors.join(";"));
ok(d.querySelectorAll("#tabs button").length === 5, "summary, one tab per pattern, and watch and method");
ok(t().includes("Failure Pattern Review FPR-2026-H1") && tab("summary").classList.contains("on"), "opens on the summary");
ok(d.querySelectorAll(".card").length === 3, "a card per pattern");
ok(d.querySelector(".chip.Landlord") && d.querySelector(".chip.Customer") && d.querySelector(".chip.IT"), "owners shown by party");
ok(t().includes("The busiest racks") && t().includes("A11"), "the ticket league table is tested, not trusted");
ok(t().includes("not proof of a bad batch"), "patterns are framed as clustering, not blame");
d.querySelector('.card[data-go="P1"]').click();
ok(t().includes("CDU-A3 ran warm") && dom.window.location.hash === "#P1", "a card opens its pattern and the address follows");
ok(d.querySelectorAll("svg").length === 2 && d.querySelectorAll("svg g.bar title").length === 26, "weekly failures and the CDU temperature, with a tooltip per week");
ok(t().includes("High-supply alarm 28.0 °C") && t().includes("FA-1"), "the alarm line and the attribution change are shown");
tab("P3").click();
ok(t().includes("Reseats do not fix XID 79") && d.querySelector(".followup") && t().includes("INC3100816"), "the September data shows the old fix still in use");
tab("method").click();
ok(t().includes("Watch items") && d.querySelectorAll("main table")[0].querySelectorAll("tr").length === 4, "every watch item with its ruling");
ok(t().includes("Bonferroni") === false && t().includes("divided by the number of tests"), "method in plain words");
const dom2 = new JSDOM(html, { runScripts: "dangerously", url: "https://example.test/patterns/#P2" });
ok(dom2.window.document.getElementById("doc").textContent.includes("LOT-2544"), "a link to a pattern opens that pattern");
ok(errors.length === 0, "still no script errors " + errors.join(";"));
