const { JSDOM } = require("jsdom");
const fs = require("fs");
const html = fs.readFileSync(process.argv[2], "utf8");
const errors = [];
const dom = new JSDOM(html, { runScripts: "dangerously", virtualConsole: new (require("jsdom").VirtualConsole)().on("jsdomError", e => errors.push(String(e))) });
const d = dom.window.document;
const t = () => d.getElementById("doc").textContent;
const ok = (c, m) => { if (!c) { console.log("FAIL:", m); process.exitCode = 1; } else console.log("ok:", m); };
ok(errors.length === 0, "no script errors " + errors.join(";"));
ok(t().includes("Rack A07 lost both power feeds"), "example renders the A07 review");
ok(t().includes("WO-41023") && t().includes("MOP-310") && t().includes("INC3900001"), "references shown");
ok(d.querySelectorAll("table")[1].rows.length > 25, "timeline table has every record");
ok(d.querySelector("svg") !== null, "swimlane drawn");
ok(t().includes("2 h 06 min past the approved window"), "MOP overrun shown");
d.getElementById("t-blank").click();
ok(d.querySelectorAll("textarea").length >= 8, "blank form has editable fields");
d.getElementById("ref").value = "wo-41023"; d.getElementById("go").click();
ok(t().includes("INC3900001") && d.querySelector("svg") !== null, "auto-fill from a work order pulls the linked ticket and draws the timeline");
d.querySelector('[data-f="pl.why"]').value = "Test reason";
d.getElementById("ref").value = "INC3100748"; d.getElementById("go").click();
ok(d.querySelector('[data-f="pl.why"]').value === "Test reason", "typed text survives a re-fill");
d.getElementById("ref").value = "NOPE"; d.getElementById("go").click();
ok(d.getElementById("refnote").textContent.includes("No P1 or P2"), "unknown reference explained");
d.getElementById("plainonly").checked = true; d.getElementById("plainonly").dispatchEvent(new dom.window.Event("change"));
ok(d.body.classList.contains("plainonly"), "plain-language toggle");
ok(errors.length === 0, "still no script errors " + errors.join(";"));
