const { JSDOM } = require("jsdom");
const fs = require("fs");
const html = fs.readFileSync(process.argv[2], "utf8");
const errors = [];
const dom = new JSDOM(html, { runScripts: "dangerously", url: "https://example.test/pir/", virtualConsole: new (require("jsdom").VirtualConsole)().on("jsdomError", e => errors.push(String(e))) });
const d = dom.window.document;
const t = () => d.getElementById("doc").textContent;
const ok = (c, m) => { if (!c) { console.log("FAIL:", m); process.exitCode = 1; } else console.log("ok:", m); };
ok(errors.length === 0, "no script errors " + errors.join(";"));
ok(t().includes("Rack A07 lost both power feeds"), "example renders the A07 review");
ok(t().includes("WO-41023") && t().includes("MOP-310") && t().includes("INC3900001"), "references shown");
ok(d.querySelectorAll("table")[1].rows.length > 25, "timeline table has every record");
ok(d.querySelector("svg") !== null, "swimlane drawn");
ok(t().includes("2 h 06 min past the approved window"), "MOP overrun shown");
ok(t().includes("Status as of 2026-09-18"), "action statuses are dated");
ok(t().includes("Not related:") && t().includes("INC3100748"), "repeat event is ruled out");
ok(t().includes("record entries only"), "badge reader note shown");
d.getElementById("t-blank").click();
ok(d.querySelectorAll("textarea").length >= 8, "blank form has editable fields");
d.getElementById("ref").value = "wo-41023"; d.getElementById("go").click();
ok(t().includes("INC3900001") && d.querySelector("svg") !== null, "auto-fill from a work order pulls the linked ticket and draws the timeline");
ok(d.querySelector('[data-f="repeat.INC3100748.related"]') !== null, "blank form asks for a ruling on each repeat event");
d.querySelector('[data-f="status_as_of"]').value = "2026-10-01";
d.querySelector('[data-f="pl.why"]').value = "Test reason";
d.getElementById("ref").value = "INC3100748"; d.getElementById("go").click();
ok(d.querySelector('[data-f="pl.why"]').value === "Test reason", "typed text survives a re-fill");
ok(d.querySelector('[data-f="status_as_of"]').value === "2026-10-01", "status date survives a re-fill");
d.getElementById("ref").value = "NOPE"; d.getElementById("go").click();
ok(d.getElementById("refnote").textContent.includes("No P1 or P2"), "unknown reference explained");
d.getElementById("plainonly").checked = true; d.getElementById("plainonly").dispatchEvent(new dom.window.Event("change"));
ok(d.body.classList.contains("plainonly"), "plain-language toggle");
ok(errors.length === 0, "still no script errors " + errors.join(";"));
// Deep links: the Overview's "Blank form" button opens /pir/#blank.
const errs2 = [];
const dom2 = new JSDOM(html, { runScripts: "dangerously", url: "https://example.test/pir/#blank", virtualConsole: new (require("jsdom").VirtualConsole)().on("jsdomError", e => errs2.push(String(e))) });
const d2 = dom2.window.document;
ok(errs2.length === 0, "no script errors on #blank " + errs2.join(";"));
ok(d2.getElementById("t-blank").classList.contains("on") && !d2.getElementById("t-example").classList.contains("on"), "#blank opens the blank form tab");
ok(d2.querySelectorAll("textarea").length >= 8, "#blank shows the editable form");
d2.getElementById("t-example").click();
ok(dom2.window.location.hash === "#example" && d2.getElementById("doc").textContent.includes("Rack A07 lost both power feeds"), "switching tabs updates the link");
ok(d.querySelector("nav.usm a.on").dataset.tab === "pir", "site tab bar marks Post-Incident Review");
