const { JSDOM, VirtualConsole } = require("jsdom");
const fs = require("fs");
const html = fs.readFileSync(process.argv[2], "utf8");
const errors = [];
const dom = new JSDOM(html, { runScripts: "dangerously", url: "https://example.test/weekly/", virtualConsole: new VirtualConsole().on("jsdomError", e => errors.push(String(e))) });
const d = dom.window.document;
const t = () => d.getElementById("doc").textContent;
const ok = (c, m) => { if (!c) { console.log("FAIL:", m); process.exitCode = 1; } else console.log("ok:", m); };
const tab = id => [...d.querySelectorAll("#tabs button")].find(b => b.dataset.week === id);

ok(errors.length === 0, "no script errors " + errors.join(";"));
ok(d.querySelectorAll("#tabs button").length === 4, "one tab per week");
ok(t().includes("Weekly Operations Review 2026-W38"), "opens on the week with meeting notes");
ok(tab("2026-W38").classList.contains("on") && tab("2026-W38").querySelector(".dot"), "that tab is selected and marked as having notes");
ok(t().includes("Below Minimum (month to date)") && d.querySelectorAll(".chip").length === 2, "a status chip for each partner");
ok(d.querySelectorAll("tr.default").length > 0, "rows below Minimum month to date are shaded");
ok(t().includes("overstated by"), "overstated self-reports are flagged");
ok(t().includes("PIR-2026-001") && d.querySelector('a[href="../pir/"]'), "the A07 outage links to its review");
ok(t().includes("D1") && t().includes("Q3"), "decisions and asks shown");
ok(d.getElementById("energy-line") && d.getElementById("energy-line").textContent.includes("PUE this week") && d.querySelector('#energy-line a[href="../energy/"]'), "the energy line links to the PUE report");
ok(d.getElementById("deploy-line") && d.getElementById("deploy-line").textContent.includes("work orders completed this week") && d.querySelector('#deploy-line a[href="../deployments/#checks"]'), "the deployment line links to the record checks");
ok(t().includes("Priorities for next week") && d.querySelectorAll("main ol li").length === 5, "next week's priorities shown for each partner");
ok(t().includes("never a weekly credit"), "weekly results are framed as early warnings");
tab("2026-W36").click();
ok(t().includes("2026-W36") && !t().includes("2026-W38") && t().includes("No meeting notes recorded"), "switching weeks re-renders without notes");
ok(dom.window.location.hash === "#2026-W36", "the selected week is in the address");
ok(t().includes("No open actions"), "no review actions before the review meeting");
tab("2026-W39").click();
ok(t().includes("dataset ends on Sep 28"), "the last week says its look-ahead runs past the data");
ok(t().includes("Not yet received"), "racks not received are listed");
const dom2 = new JSDOM(html, { runScripts: "dangerously", url: "https://example.test/weekly/#2026-W37" });
ok(dom2.window.document.getElementById("doc").textContent.includes("Weekly Operations Review 2026-W37"), "a link to a week opens that week");
ok(errors.length === 0, "still no script errors " + errors.join(";"));
