#!/usr/bin/env python3
"""Render the deployment program: docs/deployments/DEPLOYMENT_PLAN.md and the Deployments tab (/deployments/).

The Hall B GB300 NVL72 rollout as gates and steps (config/deployments.yaml), the calculation sheet from the
site model, the authority and statewide determinations, and each rack's reported and measured milestones
(src/scorecard/deployments.py).

Usage:
    python scripts/render_deployments.py            # write docs/deployments/DEPLOYMENT_PLAN.md
    python scripts/render_deployments.py --check    # fail if it is stale (CI)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from scorecard import deployments as D  # noqa: E402
from scorecard import sitenav  # noqa: E402

OUT = ROOT / "docs" / "deployments" / "DEPLOYMENT_PLAN.md"
KIND = {"internal": "Internal", "third_party": "Third party", "ahj": "Authority"}


def num(x: float, unit: str) -> str:
    return f"{x:,.1f} {unit}" if unit in ("kPa", "K", "LPM") else f"{x:,.0f} {unit}"


def stamp(iso: str | None) -> str:
    return iso[:16].replace("T", " ") + " UTC" if iso else "-"


def markdown(b: dict) -> str:
    p, roles = b["program"], b["roles"]
    role = lambda r: f"{roles[r]['name']}"
    L = [f"# {p['name']}", "",
         "*Generated by `scripts/render_deployments.py` from `config/deployments.yaml`, `site/site.yaml`, the IT Partner SLA, "
         "and the sample data. Do not edit by hand.*", "",
         f"> {' '.join(b['meta']['disclaimer'].split())} Checked {b['meta']['checked']}.", "",
         f"{p['hall_name']}: {p['racks_total']} {p['rack_model']} racks in {p['waves_total']} waves (one per row), "
         f"rack cycle target {p['cycle_days']} days. Program {p['id']}.", "",
         "## Contents", "", "1. [Gates](#gates)", "2. [Authority and permits](#authority-and-permits)",
         "3. [Statewide determinations](#statewide-determinations)", "4. [Calculation sheet](#calculation-sheet)",
         "5. [Cabling and connections](#cabling-and-connections)", "6. [Rack status](#rack-status)",
         "7. [Steps](#steps)", "8. [Record](#record)", "9. [Sign-off roles](#sign-off-roles)", "10. [Sources](#sources)", "",
         "## Gates", "", "| Gate | Name | Owner | Steps | Exit criteria |", "|---|---|---|---|---|"]
    for g in b["gates"]:
        n = sum(1 for s in b["steps"] if s["gate"] == g["id"])
        L.append(f"| {g['id']} | {g['name']} | {role(g['owner'])} | {n}{' per rack' if g['per_rack'] else ''} | {g['exit']} |")
    a = b["authority"]
    L += ["", "## Authority and permits", "", f"**Profile in use: {a['name']}** (`{a['id']}`; the other profile: "
          + ", ".join(f"{v} (`{k}`)" for k, v in b["profiles"].items() if k != a["id"]) + ").", "", a["summary"], "",
          "| Permit | Issued by | When | Inspections |", "|---|---|---|---|"]
    for pm in a["permits"]:
        L.append(f"| {pm['id']} {pm['name']} | {role(pm['by'])} | {pm['when']} | {'; '.join(pm['inspections']) or '-'} |")
    L += ["", "## Statewide determinations", "", "| Item | Requirement | What the site model says |", "|---|---|---|"]
    for d in b["statewide"]:
        L.append(f"| {d['id']} {d['name']} | {d['detail']} | {d['result']} |")
    L += ["", "## Calculation sheet", "",
          "Every check reads the site model. Checks at the reported peak that fail are not design errors: they name the control "
          "that keeps the design figure true.", "",
          "| Group | Check | Load | Capacity | Utilization | Limit | Result | Basis |", "|---|---|---|---|---|---|---|---|"]
    for r in b["calc"]:
        if r["passed"] is None:
            L.append(f"| {r['group']} | {r['check']} | {num(r['load'], r['unit'])} | - | - | - | Figure | {r['basis']} |")
        else:
            res = "Pass" if r["passed"] else f"**Control:** {r['control']}" if r["control"] else "**Fail**"
            L.append(f"| {r['group']} | {r['check']} | {num(r['load'], r['unit'])} | {num(r['capacity'], r['unit'])} | "
                     f"{r['utilization']:.0%} | {r['limit']:.0%} | {res} | {r['basis']} |")
    L += ["", "Calculation inputs the site model does not hold:", ""]
    for k, v in b["calc_inputs"].items():
        L.append(f"- `{k}` = {v['value']}: {v['basis']}")
    c = b["cabling"]
    L += ["", "## Cabling and connections", "", "Counted from the device directory (the site model).", "",
          "| Item | Count |", "|---|---|",
          f"| Racks | {c['racks']} |", f"| Compute trays | {c['compute_trays']} |", f"| InfiniBand rails per tray | {c['rails']} |",
          f"| Leaf switches | {c['leaf_switches']} |", f"| Back-end links (tray to leaf) | {c['backend_links']:,} ({c['links_per_rack']} per rack) |",
          f"| Power cords (A and B, one per tap-off) | {c['power_cords']} |", f"| Coolant hoses (supply and return) | {c['coolant_hoses']} |"]
    rk = b["racks"]
    L += ["", "## Rack status", "",
          f"As of {stamp(rk['as_of'])}, the end of the sample window. Reported: the IT Partner's milestone report. Measured: the "
          "Customer's 24-hour burn-in record and the scheduler's Validated Handoff (the CSL-09 measurement).", "",
          "| State | Racks |", "|---|---|"]
    L += [f"| {k} | {v} |" for k, v in sorted(rk["counts"].items())]
    L += ["", "| Rack | Wave | Power group | Planned receipt | Committed handoff | Last reported | Measured burn-in | Measured handoff | State |",
          "|---|---|---|---|---|---|---|---|---|"]
    for r in rk["racks"]:
        L.append(f"| {r['rack']} | {r['wave']} | {r['group']} | {stamp(r['planned_receipt'])} | {stamp(r['committed_handoff'])} | "
                 f"{r['last_reported'] or '-'} | {stamp(r['measured_burn_in'])} | {stamp(r['measured_handoff'])} | {r['state']} |")
    L += ["", "## Steps", ""]
    for g in b["gates"]:
        L += [f"### {g['id']} {g['name']}", ""]
        for s in [s for s in b["steps"] if s["gate"] == g["id"]]:
            head = f"#### {s['id']} {s['name']}"
            L += [head, "", f"- **Document:** {s['doc']['id']} ({s['doc']['kind']})", f"- **Performed by:** {role(s['owner'])}"]
            if s.get("milestone"):
                L.append(f"- **Rack milestone:** {s['milestone']}, target day {s['target_days']} from receipt (IT Partner SLA)")
            if s.get("level"):
                L.append(f"- **Commissioning level:** {s['level']}")
            if s["after"]:
                L.append(f"- **After:** {', '.join(s['after'])}")
            if s.get("when"):
                L.append(f"- **When:** {s['when']}")
            if s["standards"]:
                L.append(f"- **Standards:** {'; '.join(b['standards'][x]['name'] for x in s['standards'])}")
            L += ["", "Procedure:", ""] + [f"{i}. {x}" for i, x in enumerate(s["procedure"], 1)]
            L += ["", "Acceptance:", ""] + [f"- {x}" for x in s["acceptance"]]
            L += ["", f"Records: {'; '.join(s['records'])}.", "",
                  f"Sign-off, in order: {' -> '.join(role(r) for r in s['signoff'])}."]
            if s["inspections"]:
                L += ["", "Inspections:", ""] + [f"- {KIND[i['kind']]}: {role(i['by'])}, {i['what']}" for i in s["inspections"]]
            L.append("")
    rec, gs = b["record"], {g["gate"]: g for g in b["gate_status"]}
    L += ["## Record", "",
          "The partners' Jira projects (read through `src/scorecard/jira_import.py` with `config/jira_fields.yaml`), the Customer's "
          "step records, sign-offs, inspections, and permits (`data/deployments/`), joined into one deployment work order per unit "
          "of work. A work order is complete when it is done, every sign-off role has signed, and every required inspection passed.", "",
          "| Gate | Work orders complete | State |", "|---|---|---|"]
    L += [f"| {g['id']} {g['name']} | {gs[g['id']]['complete']} of {gs[g['id']]['total']} | {'closed' if gs[g['id']]['closed'] else 'open'} |"
          for g in b["gates"]]
    L += ["", "| Jira project | Partner | Issues | Done | In progress | Open |", "|---|---|---|---|---|---|"]
    L += [f"| {k} {v['name']} | {v['partner']} | {v['issues']} | {v['by_state']['done']} | {v['by_state']['in progress']} | {v['by_state']['open']} |"
          for k, v in rec["projects"].items()]
    L += ["", "Program work orders (rack work orders are listed on the tab):", "",
          "| Work order | Step | Source | Done | Signed | Complete |", "|---|---|---|---|---|---|"]
    L += [f"| {w['id']} | {w['step']} | {w['source']} | {stamp(w['done'])} | {w['signed']} of {len(w['signoffs'])} | {'yes' if w['complete'] else 'no'} |"
          for w in rec["work_orders"] if not w["rack"]]
    L += ["", "Permit register (fictional numbers):", "", "| Permit | Number | Issued | Finaled | Status |", "|---|---|---|---|---|"]
    L += [f"| {p['permit']} {p['name']} | {p['number'] or '-'} | {stamp(p.get('issued'))} | {stamp(p.get('finaled'))} | {p['status']}"
          f"{': ' + p['reason'] if p.get('reason') else ''} |" for p in rec["permits"]]
    L += ["", "Inspection records:", "", "| Record | Step | By | When | Result | Note |", "|---|---|---|---|---|---|"]
    L += [f"| {i['id']} | {i['step']} | {role(i['by'])} | {stamp(i['at'])} | {i['result']} | {i['note'] or '-'} |" for i in rec["inspections"]]
    L += ["", "Determinations recorded:", ""]
    L += [f"- {d['id']} ({stamp(d['recorded'])}, {d['step']}): {d['result']}" for d in rec["determinations"]]
    L += ["", "## Sign-off roles", "", "| Role | Organization | Duty |", "|---|---|---|"]
    L += [f"| {v['name']} | {v['org']} | {v['duty']} |" for v in roles.values()]
    L += ["", "## Sources", ""]
    L += [f"- {k}: {v}" for k, v in b["sources"].items()]
    return "\n".join(L) + "\n"


def prepare() -> dict:
    b = D.build()
    b["program"]["racks_total"] = len(b["racks"]["racks"])
    b["program"]["waves_total"] = len({r["wave"] for r in b["racks"]["racks"]})
    return b


def html_page() -> str:
    tpl = sitenav.inject((ROOT / "templates" / "deployments.html").read_text(encoding="utf-8"), "deployments")
    return sitenav.finish(tpl.replace("__DATA__", json.dumps(prepare(), sort_keys=True).replace("</", "<\\/")))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--html", metavar="OUT", help="also write the page")
    args = ap.parse_args()
    b = prepare()
    text = markdown(b)
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is out of date. Run: python scripts/render_deployments.py")
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    if args.html:
        out = Path(args.html)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(html_page(), encoding="utf-8", newline="\n")
    controls = sum(1 for r in b["calc"] if r["control"])
    wos = b["record"]["work_orders"]
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(b['steps'])} steps in {len(b['gates'])} gates, "
          f"{sum(1 for r in b['calc'] if r['passed'] is not None)} checks ({controls} need the power-limit control), "
          f"racks {b['racks']['counts']}, {sum(w['complete'] for w in wos)} of {len(wos)} work orders complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
