#!/usr/bin/env python3
"""Render the Weekly Operations Review: one Markdown pack per week in docs/weekly/ and the interactive page.

Usage:
    python scripts/render_weekly.py                 # write docs/weekly/*.md
    python scripts/render_weekly.py --check         # fail if docs/weekly/ is stale (CI)
    python scripts/render_weekly.py --html OUT.html # write the interactive page (scripts/build_site.py does this)
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from scorecard.weekly import STATUS_TEXT, WeeklyData, build_all  # noqa: E402

SAMPLE = ROOT / "data" / "sample"
NOTES = ROOT / "weekly" / "notes"
OUT = ROOT / "docs" / "weekly"
CENTRAL = timezone(timedelta(hours=-5), "CDT")      # the sample month is entirely in daylight time
CHIP = {"On track": "ok", "At risk": "warn", "Below Minimum (month to date)": "bad"}


def local(iso: str | None, with_day: bool = True) -> str:
    if not iso:
        return "—"
    t = datetime.fromisoformat(iso.replace("Z", "+00:00")).astimezone(CENTRAL)
    return f"{t:%a %b} {t.day}, {t:%H:%M} CDT" if with_day else f"{t:%H:%M} CDT"


def day(iso: str) -> str:
    t = datetime.fromisoformat(iso.replace("Z", "+00:00"))
    return f"{t:%b} {t.day}"


def value(v: float | None, minimum: float) -> str:
    if v is None:
        return "—"
    places = 4 if minimum >= 99.9 else 2 if minimum >= 99 else 1
    return f"{v:.{places}f}%"


def notes() -> dict[str, dict]:
    return {p.stem: yaml.safe_load(p.read_text(encoding="utf-8")) for p in sorted(NOTES.glob("*.yaml"))}


def prepare(w: dict) -> dict:
    """Add the display strings both the Markdown and the page print, so the two never disagree."""
    w["title"] = f"Week {w['number']} of {w['of']}: {day(w['start'])} to {day((datetime.fromisoformat(w['end'].replace('Z', '+00:00')) - timedelta(days=1)).isoformat())}"
    w["prepared_local"] = local(w["prepared"])
    for p in w["partners"]:
        p["chip"] = CHIP[p["status"]]
        for r in p["levels"]:
            r["week_txt"], r["mtd_txt"] = value(r["week"], r["minimum"]), value(r["mtd"], r["minimum"])
            r["reported_txt"] = value(r["reported"], r["minimum"])
            r["min_txt"] = ("≤ " if r["direction"] == "lower_is_better" else "≥ ") + value(r["minimum"], r["minimum"])
            r["week_status_txt"], r["mtd_status_txt"] = STATUS_TEXT[r["week_status"]], STATUS_TEXT[r["mtd_status"]]
            # Only a report more favorable than the measurement matters for accountability.
            r["gap_txt"] = "" if r["gap"] is None or r["gap"] < 0.0005 else f"overstated by {r['gap']:.2f} pts"
    inc = w["incidents"]
    for r in inc["it"]["p1"] + inc["it"]["p2_exceptions"] + inc["landlord"]:
        r["t0_local"] = local(r["t0"])
        r["result"] = "Open at week end" if r["met"] is None else "Met" if r["met"] else "Missed"
    for f in w["findings"]["new"]:
        f["known_local"] = local(f["known"])
    la = w["lookahead"]
    la["title"] = f"{day(la['from'])} to {day((datetime.fromisoformat(la['to'].replace('Z', '+00:00')) - timedelta(days=1)).isoformat())}"
    for m in la["mops"] + la["changes"]:
        m["when"] = local(m["window_start"])
    for p in la["maintenance"]:
        p["due"] = day(p["due_end"])
    for h in la["handoffs_due"] + la["handoffs_late"]:
        h["due"] = day(h["committed_handoff"])
    for r in la["receipts_overdue"]:
        r["planned"] = day(r["planned_receipt"])
    for s in w["resources"]["staffing"]:
        s["week_txt"], s["status_txt"] = value(s["week"], s["minimum"]), STATUS_TEXT[s["status"]]
    for k in w["resources"]["spares"]:
        k["actual_txt"] = value(k["actual"], 0)
    return w


def _table(head: list[str], rows: list[list[str]]) -> list[str]:
    return ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)] + ["| " + " | ".join(str(c).replace("|", "/") for c in r) + " |" for r in rows]


def markdown(w: dict, n: dict | None) -> str:
    L = [f"<!-- GENERATED by scripts/render_weekly.py from the dataset{' and weekly/notes/' + w['id'] + '.yaml' if n else ''}. Do not edit by hand. -->", "",
         f"# Weekly Operations Review {w['id']}", "",
         f"**Site AUS-1 (fictional).** {w['title']}. Prepared {w['prepared_local']} from data through the end of the week. "
         "Interactive version: [Weekly Operations Review page](https://jasonmossotti.github.io/dco-vendor-scorecard/weekly/).", "",
         "> Weekly results are early warnings. The contract settles service levels and credits monthly, so this pack shows "
         "each service level for the week and for the month to date, and never a weekly credit.", ""]
    if n:
        L += [f"**Meeting:** {n['meeting']} · **Chair:** {n['chair']} · **Attendees:** {', '.join(n['attendees'])}", ""]
    L += ["## 1. Status", ""]
    L += _table(["Partner", "Status", "Why"], [[f"{p['name']} ({p['role']})", f"**{p['status']}**", "; ".join(p["reasons"]) or "All service levels at or above Expected"] for p in w["partners"]])
    if n:
        L += [""] + [f"**{k}:** {v}" for k, v in n["commentary"].items()]
    L += ["", "## 2. Service levels (week and month to date)", ""]
    for p in w["partners"]:
        L += [f"### {p['name']} ({p['role']})", ""]
        L += _table(["ID", "Service level", "Minimum", "This week", "Self-reported", "Month to date", "Month to date status"],
                    [[r["id"], r["name"], r["min_txt"], f"{r['week_txt']} · {r['week_status_txt']}", r["reported_txt"] + (f" ({r['gap_txt']})" if r["gap_txt"] else ""),
                      r["mtd_txt"], f"**{r['mtd_status_txt']}**" if r["mtd_status"] in ("below_minimum", "deep_below_minimum") else r["mtd_status_txt"]] for r in p["levels"]])
        L.append("")
    inc = w["incidents"]
    L += ["## 3. Incidents", "", "P1 incidents in full; P2 incidents summarized with every one that missed its target or was still open at the end of the week. "
          "Restore times are the SLA clock (Telemetry of Record, to Validated RTS).", ""]
    it = inc["it"]
    rows = [[r["priority"], ", ".join(r["tickets"]), r["fault_class"], r["unit"], r["t0_local"], r["restore"] or "—", r["target"], r["result"],
             ("Facility-caused; IT clock from the Landlord's handoff (FA-3). " if r["facility_caused"] else "") + (f"Reviewed in {r['pir']['id']}" if r["pir"] else "")]
            for r in it["p1"] + it["p2_exceptions"]]
    L += [f"**IT Partner:** {len(it['p1'])} P1; {it['p2_count']} P2, {it['p2_met']} restored within target.", ""]
    L += _table(["Priority", "Tickets", "Class", "Unit", "Start (Central)", "SLA clock", "Target", "Result", "Notes"], rows) if rows else ["No P1 incidents and no P2 exceptions."]
    L += ["", f"**Landlord:** {len(inc['landlord'])} P1 and P2 facility events.", ""]
    rows = [[r["priority"], r["work_order"] or "—", r["unit"], r["description"], r["t0_local"], r["restore"] or "—", r["target"], r["result"],
             f"{r['owner']} ({r['rule']})" + (f"; reviewed in {r['pir']['id']}" if r["pir"] else "")] for r in inc["landlord"]]
    L += _table(["Priority", "Work order", "Unit", "What", "Start (Central)", "Restore", "Target", "Result", "Owner"], rows) if rows else ["No P1 or P2 facility events."]
    fd = w["findings"]
    L += ["", "## 4. New findings", "", f"Raised this week, in the week each discrepancy was observed. {fd['awaiting_monthly_review']} findings so far this month go to the monthly "
          "service review, where corrective action plans are raised. A finding means the records do not reconcile, not that anyone acted in bad faith.", ""]
    L += _table(["ID", "Partner", "Severity", "Finding", "Summary", "Observed"],
                [[f["id"], f["partner"], f["severity"], f["title"], f["summary"], f["known_local"]] for f in fd["new"]]) if fd["new"] else ["No new findings."]
    L += ["", "## 5. Open actions", ""]
    if w["actions"]:
        L += [f"From completed post-incident reviews. Status as recorded on {w['actions'][0]['status_as_of']}.", ""]
        L += _table(["Source", "ID", "Action", "Owner", "Priority", "Due", "Status"],
                    [[a["source"], a["id"], a["action"], a["owner"], a["priority"], a["due"], a["status"] + (" (**overdue**)" if a["overdue"] else "")] for a in w["actions"]])
    else:
        L += ["No open actions from post-incident reviews."]
    la = w["lookahead"]
    L += ["", f"## 6. Look-ahead: {la['title']}", "", "Only work approved or scheduled by the end of this week."
          + (" The dataset ends on Sep 28, so anything planned after that is not shown." if la["beyond_data"] else ""), ""]
    L += ["**Landlord MOPs approved for next week:** " + ("; ".join(f"{m['id']} {m['title']} ({m['when']})" for m in la["mops"]) or "none"),
          "", "**IT changes approved for next week:** " + ("; ".join(f"{c['id']} {c['summary']} ({c['when']})" for c in la["changes"]) or "none")
          + " (the change records do not carry an approval time)",
          "", "**Maintenance due:** " + ("; ".join(f"{p['id']} {p['asset']} {p['task']} (due {p['due']})" for p in la["maintenance"]) or "none"),
          "", "**Hall B handoffs due:** " + ("; ".join(f"{h['rack']} on {h['due']} (now at {h['milestone']} {h['milestone_name']})" for h in la["handoffs_due"]) or "none"),
          "", "**Hall B handoffs past commitment:** " + ("; ".join(f"{h['rack']} (committed {h['due']}, at {h['milestone']} {h['milestone_name']})" for h in la["handoffs_late"]) or "none"),
          "", "**Hall B racks not yet received:** " + ("; ".join(f"{r['rack']} (planned {r['planned']}, {r['days_overdue']} day{'' if r['days_overdue'] == 1 else 's'} late)" for r in la["receipts_overdue"]) or "none"),
          "", f"**Rostered shifts next week:** IT Partner {la['rostered_shifts']['it']}, Landlord {la['rostered_shifts']['landlord']}"]
    rs = w["resources"]
    L += ["", "## 7. Resources", ""]
    L += _table(["Measure", "This week", "Target", "Detail"],
                [[f"{s['id']} {s['name']}", f"{s['week_txt']} · {s['status_txt']}", f"≥ {s['minimum']}%", s["detail"]] for s in rs["staffing"]]
                + [[f"{k['id']} {k['name']}", k["actual_txt"], f"≥ {k['target']}%", k["detail"]] for k in rs["spares"]])
    L += ["", f"Failed parts awaiting shipment to the OEM at the end of the week: {rs['rma_open']}"
          + (f" (oldest removed {rs['rma_oldest_days']} days ago)." if rs["rma_open"] else ".")]
    e = w["ehs"]
    L += ["", "## 8. Safety (EHS)", "", f"- **Injuries this week:** {e['injuries']}"]
    L += [f"- **Event:** {x['pir']}: {x['screening']}" for x in e["events"]]
    L += [f"- **Open investigation:** {x['pir']} action {x['action']}, due {x['due']}{' (**overdue**)' if x['overdue'] else ''}. {x['referral']}" for x in e["open_investigations"]]
    if not e["events"] and not e["open_investigations"]:
        L.append("- No events and no open investigations.")
    L += ["", "## 9. Decisions, priorities, and asks", ""]
    if n:
        L += ["**Decisions**", ""] + [f"- **{x['id']}** ({x['owner']}): {x['text']}" for x in n["decisions"]]
        L += ["", "**Priorities for next week**, set by the Customer Site Lead, in order:", ""]
        for role in ("IT Partner", "Landlord"):
            L += [f"- **{role}:**"] + [f"  {i}. {x['text']}" for i, x in enumerate((p for p in n["priorities"] if p["to"] == role), 1)]
        L += ["", "**Asks**"]
        L += [""] + _table(["Ask", "To", "Due", "Request"], [[x["id"], x["to"], x["due"], x["text"]] for x in n["asks"]])
    else:
        L += ["No meeting notes recorded for this week; the facts above stand on their own."]
    L += ["", "*Synthetic data for a portfolio demonstration; all names and events are fictional.*", ""]
    return "\n".join(L)


def packs() -> list[dict]:
    return [prepare(w) for w in build_all(WeeklyData(SAMPLE))]


def outputs() -> dict[Path, str]:
    nt = notes()
    return {OUT / f"{w['id']}.md": markdown(w, nt.get(w["id"])) for w in packs()}


def html_page() -> str:
    data = {"weeks": packs(), "notes": notes()}
    tpl = (ROOT / "templates" / "weekly.html").read_text(encoding="utf-8")
    return tpl.replace("__DATA__", json.dumps(data, sort_keys=True).replace("</", "<\\/"))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--html", metavar="OUT")
    args = ap.parse_args()
    if args.html:
        Path(args.html).parent.mkdir(parents=True, exist_ok=True)
        Path(args.html).write_text(html_page(), encoding="utf-8")
        print(f"Wrote {args.html}")
        return 0
    docs = outputs()
    if args.check:
        stale = [p for p, t in docs.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
        stale += [p for p in OUT.glob("*.md") if p not in docs]
        for p in stale:
            print(f"{p.relative_to(ROOT)} is out of date. Run: python scripts/render_weekly.py")
        return 1 if stale else 0
    OUT.mkdir(parents=True, exist_ok=True)
    for p in OUT.glob("*.md"):
        if p not in docs:
            p.unlink()
    for p, t in docs.items():
        p.write_text(t, encoding="utf-8", newline="\n")
        print(f"Wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
