#!/usr/bin/env python3
"""Render post-incident reviews: the Markdown review in docs/pir/ and the interactive page for GitHub Pages.

Usage:
    python scripts/render_pir.py                 # write docs/pir/*.md
    python scripts/render_pir.py --check         # fail if docs/pir/ is stale (CI)
    python scripts/render_pir.py --html OUT.html # write the interactive page (scripts/build_site.py does this)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from scorecard.pir import OSR, Dataset, build_index, build_review  # noqa: E402

SAMPLE = ROOT / "data" / "sample"
REVIEWS = ROOT / "pir" / "reviews"
OUT = ROOT / "docs" / "pir"


def reviews() -> list[dict]:
    return [yaml.safe_load(p.read_text(encoding="utf-8")) for p in sorted(REVIEWS.glob("*.yaml"))]


def markdown(f: dict, a: dict) -> str:
    pl, sev, ehs, ls = a["plain_language"], a["severity"], a["ehs"], a["lessons"]
    im = f["impact"]
    L = [f"<!-- GENERATED by scripts/render_pir.py from pir/reviews/{a['id']}.yaml and the dataset. Do not edit by hand. -->", "",
         f"# {a['id']}: {a['title']}", "",
         f"**Status:** {a['status']} · **Blameless review:** findings describe systems and procedures, not individuals. "
         f"Interactive version: [Post-Incident Review page](https://jasonmossotti.github.io/dco-vendor-scorecard/pir/).", "",
         "| Incident date | Ticket | Work order | MOP | Unit | Uptime severity (OSR) | Internal severity | Priority | Incident Commander | Review meeting |",
         "|---|---|---|---|---|---|---|---|---|---|",
         f"| {f['date']} | {f['ticket']} | {f['work_order']} | {', '.join(f['mops'])} | {f['unit']} | {sev['osr_level']} {OSR[sev['osr_level']][0]} | "
         f"{sev['internal']} | {sev['priority']} | {a['incident_commander']} | {a['review_meeting']} |", "",
         f"*OSR {sev['osr_level']} ({OSR[sev['osr_level']][0]}): {OSR[sev['osr_level']][1]} {sev['osr_rationale']}*", "",
         "## In plain language", ""]
    for q, k in (("What happened?", "what_happened"), ("Who was affected?", "who_was_affected"), ("Why did it happen?", "why"),
                 ("What are we doing about it?", "what_we_are_doing")):
        L += [f"**{q}** {pl[k]}", ""]
    L += ["| Power loss to back in service | GPUs offline | GPU-hours lost | GPU-hours: Landlord / IT validation | Injuries |",
          "|:-:|:-:|:-:|:-:|:-:|", f"| {im['duration']} | {im['gpus']} | {im['gpu_hours_total']} | {im['gpu_hours_landlord']} / {im['gpu_hours_it']} | {im['injuries']} |", "",
          "## Summary (technical)", "", a["summary_technical"], "",
          f"- **Trigger:** {a['trigger']}", f"- **Detection:** {a['detection']}", f"- **Resolution:** {a['resolution']}", "",
          "## Response against targets", "", "| Measure | From (UTC) | To (UTC) | Elapsed | Target | Result |", "|---|---|---|---|---|---|"]
    for m in f["metrics"]:
        L.append(f"| {m['measure']} | {m['from'][11:19]} | {m['to'][11:19]} | {m['elapsed']} | {str(m['target']) + ' min' if m['target'] else '—'} | "
                 f"{'—' if m['met'] is None else 'Met' if m['met'] else '**Missed**'} |")
    L += ["", "## Alarm and event timeline (exact source records)", "", "| UTC | Central | Party | Event | Source | Record |", "|---|---|---|---|---|---|"]
    for r in f["timeline"]:
        L.append(f"| {r['t'][11:19]} | {r['local']} | {r['party']} | {r['event'].replace('|', '/')} | `{r['source']}` | "
                 f"{('`' + r['record'].replace('|', '/') + '`') if r['record'] else ''} |")
    at = f["attribution"]
    L += ["", "## Attribution (Interface Agreement)", "", f"**Owner: {at['owner']}** (rules {', '.join(at['rules'])}). {at['evidence']}. "
          f"Under FA-3 the IT Partner's clock started at the Landlord's handoff, {f['handoff'][11:19]}Z.", "",
          "## Contract and compliance consequences", ""]
    L += [f"- Finding {x['id']} ({x['severity']}): {x['summary']}" for x in f["findings"]]
    c = f["csl"].get("OT-CSL-01")
    if c:
        L.append(f"- OT-CSL-01 Rack Power Availability measured {c['actual']:.4f}% against a Minimum of {c['minimum']}%: "
                 f"{c['status'].replace('_', ' ')}" + (f", credit ${c['credit']:,.0f}." if c["credit"] else "."))
    if f["mop_overrun"]:
        o = f["mop_overrun"]
        L.append(f"- {o['mop']} window ended {o['window_end'][11:19]}Z; its equipment was closed at {o['closed'][11:19]}Z, {o['overrun']} past the approved window.")
    L += ["", "## EHS screening", "", f"- **Injuries:** {ehs['injuries']}", f"- **Screening:** {ehs['screening']}", f"- **Referral:** {ehs['referral']}", "",
          "## Contributing factors", "", "| ID | Type | Factor |", "|---|---|---|"]
    L += [f"| {x['id']} | {x['type']} | {x['text']} |" for x in a["factors"]]
    for t, k in (("What went well", "went_well"), ("What went poorly", "went_poorly"), ("Where we got lucky", "lucky")):
        L += ["", f"## {t}", ""] + [f"- {x}" for x in ls[k]]
    L += ["", "## Action items", "", "| ID | Action | Factor | Owner | Priority | Due | Success criterion | Status |", "|---|---|---|---|---|---|---|---|"]
    L += [f"| {x['id']} | {x['action']} | {x['factor']} | {x['owner']} | {x['priority']} | {x['due']} | {x['success']} | {x['status']} |" for x in a["actions"]]
    L += ["", "## Communications log", "", "| Time | To | Message |", "|---|---|---|"]
    L += [f"| {x['local']} | {x['to']} | {x['message']} |" for x in a["communications"]]
    if f["repeats"]:
        L += ["", "## Repeat-event check", "", "Other records in the window on the same rack or busway; each is ruled in or out as related.", ""]
        L += [f"- {r['ref']} ({r['opened'][:16].replace('T', ' ')}Z): {r['what']}" for r in f["repeats"]]
    L += ["", "## Sign-off", "", "| Role | Signed |", "|---|---|"] + [f"| {s['role']} | {s['date']} |" for s in a["signoff"]]
    L += ["", "*Synthetic data for a portfolio demonstration; all names and events are fictional.*", ""]
    return "\n".join(L)


def outputs() -> dict[Path, str]:
    ds = Dataset(SAMPLE)
    out = {}
    for a in reviews():
        f = build_review(ds, a["ref"])
        out[OUT / f"{a['id']}.md"] = markdown(f, a)
    return out


def html_page() -> str:
    ds = Dataset(SAMPLE)
    rv = reviews()
    data = {"index": build_index(ds), "example": rv[0], "osr": {k: list(v) for k, v in OSR.items()}}
    tpl = (ROOT / "templates" / "pir.html").read_text(encoding="utf-8")
    return tpl.replace("__DATA__", json.dumps(data, sort_keys=True).replace("</", "<\\/"))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--html", metavar="OUT")
    args = ap.parse_args()
    if args.html:
        Path(args.html).parent.mkdir(parents=True, exist_ok=True)
        Path(args.html).write_text(html_page(), encoding="utf-8")
        print(f"Wrote {args.html}")
        return 0
    docs = outputs()
    if args.check:
        stale = [p for p, t in docs.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
        for p in stale:
            print(f"{p.relative_to(ROOT)} is out of date. Run: python scripts/render_pir.py")
        return 1 if stale else 0
    OUT.mkdir(parents=True, exist_ok=True)
    for p, t in docs.items():
        p.write_text(t, encoding="utf-8", newline="\n")
        print(f"Wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
